### ISSUE TITLE
Payment type cannot be set for an order

### ISSUE THREAD

**Issue by klapperkopp** [bookingkit/bookingkit-API-v3#10]
Problem:
When I post a new order (reservation) I cannot set the payment type. ALso on existing orders I cannot change the payment type, which is related to #9.

What's expected:
I'd like to be able to set the payment type for reservations to "online" in an API-Call as it is also possible in the UI. I would expect this to happen either by adding a payment-object while creating the order or use the payments api endpoint for an order after creating it.

**Comment by victorRadu** [comment]
hello please send your request to service@bookkingit.de. Do not forget to add your client_id, the request you send and the response you get. Thank you.
