### ISSUE TITLE
category.json is invalid

### ISSUE THREAD

**Issue by drAlberT** [bookingkit/bookingkit-API-v3#5]
it has both wrong file name and a broken content

**Comment by victorRadu** [comment]
the category endpoint is still "under construction" we will be finalising it soon.

**Comment by drAlberT** [comment]
ok, but if I download the API from GH I can't import it on postman or other converters ... I kindly suggest to drop GH Releases to allow ppl to download stable versions of the API ..

**Comment by karazeyandrey** [comment]
Should be fine now.
