### ISSUE TITLE
Posting an order as "PENDING" creates an "ACCEPTED" order

### ISSUE THREAD

**Issue by klapperkopp** [bookingkit/bookingkit-API-v3#9]
Problem:
I cannot create reservations, but only orders.

What happens:
In the sandbox, creating an order with the status "PENDING" and an "expire_date" set, the system will return an order with status "ACCEPTED".

What's expected:
The system returns an order with status "PENDING" or "RESERVED".

**Comment by victorRadu** [comment]
hello please send your request to service@bookkingit.de. Do not forget to add your client_id, the request you send and the response you get. Thank you.
